
north: '&e&lN'
north-selected: '&6&lN'

east: '&e&lE'
east-selected: '&6&lE'

south: '&e&lS'
south-selected: '&6&lS'

west: '&e&lW'
west-selected: '&6&lW'

fill: '&7═'
fill-select: '&f╩'

fill-center: '&7╪'
fill-center-select: '&f╪'

default:
  compass-target: '&f◇'
  compass-target-selected: '&f◆'

  compass-target-above: '&f△'
  compass-target-selected-above: '&f▲'

  compass-target-below: '&f▽'
  compass-target-selected-below: '&f▼'

selected:
  compass-target: '&2◇'
  compass-target-selected: '&a◆'

  compass-target-above: '&2△'
  compass-target-selected-above: '&a▲'

  compass-target-below: '&2▽'
  compass-target-selected-below: '&a▼'

title-prefix: '&6'

symbol-start: '&e&l╠'
symbol-end: '&e&l╣'

bar-color: white
bar-style: solid

ticks-update-compass: 2

y-difference-icons: 10