name: HonnyCompass
version: '${project.version}'
main: honny.HonnyCompass
api-version: 1.18

depend:
  - BetonQuest

softdepend:
  - PlaceholderAPI
  - AuthMe

commands:
  honnycompass:
    usage: '§e/honnycompass'
    aliases: [ hcompass ]