name: HonnyCompass
version: '${project.version}'
main: honny.HonnyCompass
api-version: 1.18

depend:
  - BetonQuest
  - PlaceholderAPI

commands:
  honnycompass-reload:
    usage: '§e/honnycompass-reload'
    permission: honnycompass.reload

permissions:
  honnycompass.reload:
    default: op
